### ISSUE TITLE
Link to Style and Coding Guide is Broken

### ISSUE THREAD

**Issue by JacobJBeck** [jredmondson/madara-contractor-test#1]
As the title says, the link on the readme to the C++ style guide is broken, and leads to a 404 error page (https://github.com/jredmondson/madara-contractor-test/blob/master/Style-and-Coding-Guide).

**Comment by jredmondson** [comment]
Link updated to https://github.com/jredmondson/madara/wiki/Style-and-Coding-Guide. Sorry about that!
